spring.application.name=TFG

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# ===============================
# Asegúrate de que el puerto (3306) y el nombre de la BD (skillswap_db) sean correctos
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CONFIGURACIÓN DE JWT (Seguridad)
# ===============================
# Esta es la firma de tus tokens de sesión. (En un entorno real estaría oculta)
jwt.secret=ClaveSecretaSuperSeguraParaMiTFGDeDesarrolloWeb2026!
jwt.expiration=86400000T

# Seguridad JWT
bezkoder.app.jwtSecret=UnaClaveSuperSecretaYMuyLargaParaElTFGDeGuilleQueNadieAdivinara123456789
bezkoder.app.jwtExpirationMs=86400000